#!/usr/bin/env php
<?php

if (file_exists(__DIR__ . '/../../autoload.php')) {
    require __DIR__ . '/../../autoload.php';
} else {
    require __DIR__ . '/vendor/autoload.php';
}

$app = new Symfony\Component\Console\Application('Assely Installer', '0.1.0');

$app->add(new Assely\Installer\Console\NewCommand);
$app->add(new Assely\Installer\Console\FetchFrameworkCommand);
$app->add(new Assely\Installer\Console\FetchFielderCommand);

$app->run();
